### ISSUE TITLE
Google Sheets App Scripts

### ISSUE THREAD

**Issue by Vikranth3140** [naveen-ravi2810/smtp_mailer#1]
Hi, just a suggestion: we can also use the Google Sheets App Scripts extension to send emails directly.
It is basically JasaScript instead of Python, though.

You can check it here - [Gmail Automation](https://github.com/Vikranth3140/Gmail-Automation)

**Comment by naveen-ravi2810** [comment]
Thanks for the suggestion.
This package is made for application developers ro minimize the email setup code.
So I have build it.
